title: SFG
email: example@example.com
description: >
  This is the Collider Jekyll Theme.
baseurl: "/"
github_username: ""
linked_in_profile: ""
full_name: Rando Dev
user_description: Software Engineer
disqus:
  shortname: jekyll-theme-collider-netlify-com

sass:
    sass_dir: assets/css